---
title: cssgrid
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cssgrid}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{css css, echo = FALSE}
body {box-sizing: border-box;}
.cssgrid p {margin: 0;}
```


```{r knit-opt, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE
)
```

```{r setup, include=FALSE}
library(cssgrid)
knitr::opts_chunk$set(echo = TRUE)
```

```{r cssgrid, echo = FALSE}
i <- function(x, ...) grid_item(x, ..., style = "border: solid black; text-align: center;")
txt <- function(x) div(x, style = "margin: 0;", class="foo")
grid_layout(
  i(txt("C"), area = "a"), i(txt("S"), area = "b"), i(txt("S"), area = "c"), 
  i(txt("grid"), area = "d"),
  cols = "1.5rem 1.5rem 1.5rem", rows = "1lh 1lh",
  areas = c("a b c", "d d d"),
  gap = ".5rem", class = "cssgrid"
)
```

```{r}
library(cssgrid)
```

# Simple examples

```{r area, results = 'asis'}
style <- "border: solid black;"
grid_layout(
  grid_item("A", area = "a", style = style),
  grid_item("B", area = "b", style = style),
  grid_item("C", area = "c", style = style),
  cols = c("1fr 2fr"), rows = c("1fr 1fr"), areas = c("a b", "a c"),
  style = style
)
```

<p></p>

```{r row-col}
grid_layout(
  grid_item("A", row = "1 / 3", col = "1 / 2", style = style),
  grid_item("B", row = "1 / 2", col = "2 / 3", style = style),
  grid_item("C", row = "2 / 3", col = "2 / 3", style = style),
  cols = c("1fr 2fr"), rows = c("1fr 1fr"), style = style
)
```
